import styles from "@/styles/Home.module.css";
import Head from "next/head";
import Link from "next/link";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header/> */}
      <main className={styles.main}>
        Helloo Home Page
        <Link href = "thongcho">to thong cho</Link>
      </main>
    </>
  );
}
