[package]
name = "aioracle_base"
version = "0.6.0"
authors = ["Oraichain "]
edition = "2018"
repository = "https://github.com/oraichain/oraiwasm"
homepage = "https://orai.io"

[dependencies]
cosmwasm-std = { version = "0.13.2" }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
cw0 = "0.5.0"


[dev-dependencies]
cosmwasm-schema = { version = "0.13.2" }
