[package]
edition = "2018"
name = "aioracle_health_check"
version = "0.1.0"

exclude = [
  "artifacts/*",
] # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = true
panic = 'abort'
rpath = false

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "0.13.0" }
cosmwasm-storage = { version = "0.13.0" }
cw-storage-plus = { version = "0.5.0", features = ["iterator"] }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.21" }
bech32 = "0.8.1"
ripemd = "0.1.1"
sha2 = { version = "0.9.5", default-features = false }
aioracle_base = {path = '../../base/aioracle_base'}

[dev-dependencies]
cosmwasm-schema = { version = "0.13.0" }
bech32 = "0.8.1"
ripemd = "0.1.1"
cw-multi-test = { version = "0.5.0" }
sha2 = { version = "0.9.5", default-features = false }
aioracle_v2 = {path = '../aioracle_v2'}
