/* eslint-disable @next/next/no-title-in-document-head */
import { Head } from 'next/head';

export function Header() {
    return(
        <>
            <Head>
            // eslint-disable-next-line @next/next/no-title-in-document-head
            <title>Agriblock App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
        </>
    )
}