[package]
name = "market_1155"
version = "0.6.0"
authors = ["ThanhTu <tu@orai.io>"]
edition = "2018"
description = "Implementation of an NFT marketplace proxy contract using a governance"
repository = "https://github.com/oraichain/oraiwasm"
homepage = "https://orai.io"

[dependencies]
cosmwasm-std = { version = "0.13.2" }
schemars = "0.7"
market = { path = "../../base/market" }
serde = { version = "1.0.103", default-features = false, features = ["derive"] }


[dev-dependencies]
cosmwasm-schema = { version = "0.13.2" }
