[package]
authors = ["Thanh tu <tu@orai.io>"]
edition = "2018"
license = "AGPL-3.0"
name = "vrfdkg"
version = "0.1.0"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "artifacts/",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = true
panic = 'abort'
rpath = false

[dependencies]
cosmwasm-std = { version = "0.13.2" }
cosmwasm-storage = { version = "0.13.2", features = ["iterator"] }
blsdkg = { path = "../../base/blsdkg" }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = "1.0"
cosmwasm-crypto = "0.14.0"
sha3 = "0.9.1"


[dev-dependencies]
cosmwasm-vm = { version = "0.13.2", default-features = false }
cosmwasm-schema = { version = "0.13.2" }
cosmwasm-crypto = "0.14.0"
sha3 = "0.9.1"
rand = "0.7.3"
pairing = "0.16.0"
